# Based on nila's work (https://community.home-assistant.io/t/ozw-aeon-labs-aeotec-zw130-wallmote-quad/256240)
# Which in turn was based on troy's work (https://community.home-assistant.io/t/ozw-aeotec-zwa003-nanomote-quad/256024)
#
# The latest version of this blueprint can be found at:
# https://github.com/kdknigga/homeassistant_blueprints/blob/master/ozw-aeon-labs-aeotec-zw130-wallmote-quad/ozw-aeon-labs-aeotec-zw130-wallmote-quad.yaml

blueprint:
  name: Aeotec ZW130 WallMote Quad OZW
  description: Create automations for the Aeotec ZW130 WallMote Quad using the OZW
    integration
  domain: automation
  input:
    aeotec_wallmote:
      name: Aeotec WallMote Quad
      description: List of available WallMote Quad remotes to configure. This list
        is only a reference. At this time, it is not possible to obtain the node's
        id using the device selector.
      selector:
        device:
          integration: ozw
#          manufacturer: AEON Labs
#          model: ZW130 WallMote Quad
    ozw_node_id:
      name: Node ID
      description: Enter the node id for an available WallMote Quad you wish to configure.
        For now, this field is required. At this time, it is not possible to obtain
        the node's id when using the device selector.
    button_1:
      name: Press Button One
      description: Action to run on button press.
      default: []
      selector:
        action: {}
    button_2:
      name: Press Button Two
      description: Action to run on button press.
      default: []
      selector:
        action: {}
    button_3:
      name: Press Button Three
      description: Action to run on button press.
      default: []
      selector:
        action: {}
    button_4:
      name: Press Button Four
      description: Action to run on button press.
      default: []
      selector:
        action: {}
  source_url: https://github.com/kdknigga/homeassistant_blueprints/blob/master/ozw-aeon-labs-aeotec-zw130-wallmote-quad/ozw-aeon-labs-aeotec-zw130-wallmote-quad.yaml
mode: single
max_exceeded: silent
variables:
  device_id: !input 'aeotec_wallmote'
  ozw_node_id: !input 'ozw_node_id'
trigger:
- platform: event
  event_type: ozw.scene_activated
  event_data:
    node_id: ( ozw_node_id | int )
action:
- variables:
    node_id: '{{ trigger.event.data.node_id }}'
    scene_id: '{{ trigger.event.data.scene_id }}'
    scene_value_id: '{{ trigger.event.data.scene_value_id }}'
- choose:
  - conditions:
    - '{{ scene_id == 1 }}'
    - '{{ scene_value_id == 1 }}'
    sequence: !input 'button_1'
  - conditions:
    - '{{ scene_id == 2 }}'
    - '{{ scene_value_id == 1 }}'
    sequence: !input 'button_2'
  - conditions:
    - '{{ scene_id == 3 }}'
    - '{{ scene_value_id == 1 }}'
    sequence: !input 'button_3'
  - conditions:
    - '{{ scene_id == 4 }}'
    - '{{ scene_value_id == 1 }}'
# Thanks Severinius-MUC for fixing Button 4 ;-)
    sequence: !input 'button_4'
